---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: production
  namespace: monitoring
spec:
  version: v2.43.1
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      prometheus: main
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: main
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: 1
  logLevel: info
  logFormat: logfmt
  retention: 6h
  scrapeInterval: 15s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: nfs-client
        resources:
          requests:
            storage: 2Gi
  remoteWrite:
  #Domain name or LoadBalancer IP of common receiver write service
    - url: http://172.17.18.210:10908/api/v1/receive
      queueConfig:
        maxSamplesPerSend: 1000
        maxShards: 200
        capacity: 2500