---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: objstore
stringData:
  objstore.yml: |-
    type: S3
    config:
      bucket: test
      endpoint: "minio.minio:9000"
      insecure: true
      access_key: "1vZ8Xi9yO83yUwuS"
      secret_key: "LQ2cE6WY0rBqu4vNSpZaYGbwZsibtUZt"
